import Text from "@/components/generic/Text";

export default function TermsAndConditions() {
    return (
        <div className="w-full min-w-[269px] flex-1 md:min-w-[304px] lg:min-w-auto">
            <div className="mx-4 mb-6 lg:mx-[172px] lg:mb-8">
                <Text
                    as="h3"
                    font="helvetica"
                    className="text-[32px] lg:text-[40px] leading-[100%] lg:leading-[48px] text-re-black md:font-semibold font-bold font-guardian mt-[24px] mb-8 tracking-[-0.64px] capitalize md:tracking-normal lg:mt-[60px] lg:w-full"
                >
                    terms and conditions{" "}
                </Text>
                <Text
                    as="p"
                    font="helvetica"
                    size="productTitle2"
                    color="black"
                    weight="light"
                    className=" mb-8"
                >
                    ROYAL ENFIELD and/or its affiliates provide website features
                    and other products and services to you when you visit or
                    shop at Royalenfield.com, use ROYAL ENFIELD products or
                    services, or use software provided by ROYAL ENFIELD in
                    connection with any of the foregoing. ROYAL ENFIELD is a
                    unit of EICHER MOTORS LIMITED, which is incorporated under
                    the Companies Act, 1956. ROYAL ENFIELD provides the Services
                    subject to the following conditions. This user agreement
                    (“Terms and Conditions” or “T&amp;C” or “Terms” or
                    “Agreement”) is between you (“you” or “End User” or “your”
                    or “Buyer” or “Customer” or “Registered User”) and EICHER
                    MOTORS LIMITED (“Company” or “us” or “we” or
                    “Royalenfield.com” or “store.royalenfield.com” or “ROYAL
                    ENFIELD” ). This document is an electronic record in terms
                    of Information Technology Act, 2000 and rules there under as
                    applicable and the amended provisions pertaining to
                    electronic records in various statutes as amended by the
                    Information Technology Act, 2000. This electronic record is
                    generated by a computer system and does not require any
                    physical or digital signatures. Notwithstanding anything
                    contained or said in any other document, if there is a
                    conflict between the terms mentioned herein below and any
                    other document, the terms contained in the present T&amp;C
                    shall alone prevail for the purposes of usage of the Site
                </Text>
                <div className="mb-6 lg:mb-8">
                    <Text
                        as="p"
                        weight="bold"
                        font="helvetica"
                        className="text-[1.25rem] mb-6 lg:mb-8 flex gap-5"
                    >
                        {" "}
                        1. INTRODUCTION
                    </Text>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            1.1. The domain name royalenfield.com is registered
                            in the name of Eicher Motors Limited which is a
                            registered company under the Companies Act, 1956.
                            Its registered office is at 3rd Floor, Select
                            Citywalk, A-3, District Centre, Saket, New Delhi
                            110017. ROYAL ENFIELD is in the business of
                            manufacture and sale of motorcycles, motorcycle
                            gear, apparel and other related goods and has
                            various retail stores located all across India.
                        </Text>
                    </div>
                </div>
                <div className="mb-6 lg:mb-8">
                    <Text
                        as="p"
                        weight="bold"
                        font="helvetica"
                        className="text-[1.25rem] mb-6 lg:mb-8 flex gap-5"
                    >
                        {" "}
                        2. THESE TERMS & CONDITIONS MAY CHANGE{" "}
                    </Text>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            {" "}
                            2.1 ROYAL ENFIELD reserves the sole right to update
                            or modify these Terms and Conditions at any time
                            without prior notice. For this reason, we encourage
                            you to review these Terms and Conditions every time
                            you purchase products from us or use our Web Site.
                        </Text>
                    </div>
                </div>
                <div className="mb-6 lg:mb-8">
                    <Text
                        as="p"
                        weight="bold"
                        font="helvetica"
                        className="text-[1.25rem] mb-6 lg:mb-8 flex gap-5"
                    >
                        {" "}
                        3. PRIVACY
                    </Text>

                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            We view protection of your privacy as a very
                            important principle. We understand clearly that You
                            and Your Personal Information is one of our most
                            important assets. We store and process Your
                            Information including any sensitive financial
                            information collected (as defined under the
                            Information Technology Act, 2000), if any, on
                            computers that may be protected by physical as well
                            as reasonable technological security measures and
                            procedures in accordance with Information Technology
                            Act 2000 and Rules there under. If you object to our
                            current Privacy Policy and your information being
                            transferred or used in this way please do not use
                            Website.
                        </Text>
                    </div>
                </div>
                <div className="mb-6 lg:mb-8">
                    <Text
                        as="p"
                        weight="bold"
                        font="helvetica"
                        className="text-[1.25rem] mb-6 lg:mb-8 flex gap-5"
                    >
                        {" "}
                        4. DISTRIBUTION OF INFORMATION
                    </Text>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            {" "}
                            When you use any of our Services, or send e-mails to
                            us, you are communicating with us electronically.
                            You by using our services consent to receive
                            communications from us electronically. We will
                            communicate with you by e-mail or by posting notices
                            on this site or through other Services. You agree
                            that all agreements, notices, disclosures and other
                            communications that we provide to you electronically
                            satisfy any legal requirement that such
                            communications be in writing. The legal requirements
                            would be inconformity with the Indian Information
                            Technology Act, 2000 and rules there under as
                            applicable and the amended provisions pertaining to
                            electronic records in various statutes as amended by
                            the Information Technology Act, 2000.
                        </Text>
                    </div>
                </div>
                <div className="mb-6 lg:mb-8">
                    <Text
                        as="p"
                        weight="bold"
                        font="helvetica"
                        className="text-[1.25rem] mb-6 lg:mb-8 flex gap-5"
                    >
                        {" "}
                        5. INTELLECTUAL PROPERTY RIGHTS{" "}
                    </Text>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            {" "}
                            5.1 Unless otherwise indicated or anything contained
                            to the contrary or any proprietary material owned by
                            a third party and so expressly mentioned, ROYAL
                            ENFIELD owns all Intellectual Property Rights to and
                            into the Website, including, without limitation, any
                            and all rights, title and interest in and to
                            copyright, related rights, patents, utility models,
                            trademarks, trade names, service marks, designs,
                            know-how, trade secrets and inventions (whether
                            patentable or not), goodwill, source code, meta
                            tags, databases, text, content, graphics, icons, and
                            hyperlinks. You acknowledge and agree that you shall
                            not use, reproduce or distribute any content from
                            the Website belonging to ROYAL ENFIELD without
                            obtaining authorization from it. 5.2 User shall not
                            upload post or otherwise make available on the Site
                            any material protected by copyright, trademark or
                            other proprietary right without the express
                            permission of the owner of the copyright, trademark
                            or other proprietary right. ROYAL ENFIELD does not
                            have any express burden or responsibility to provide
                            the Users with indications, markings or anything
                            else that may aid the User in determining whether
                            the material in question is copyrighted or
                            trademarked. User shall retain ownership, if any,
                            and shall be solely responsible for any content that
                            User provides or upload when using any service on
                            the Site, including any text, data, information,
                            images, photographs, music, sound, video or any
                            other material which User may upload, transmit or
                            store and User shall also be solely liable for any
                            damage resulting from any infringement of
                            copyrights, trademarks, proprietary rights or any
                            other harm resulting from such a submission. By
                            submitting material to any public area of the Site,
                            User warrants that the owner of such material has
                            expressly granted ROYAL ENFIELD the royalty-free,
                            perpetual, irrevocable, non-exclusive right and
                            license to use, reproduce, modify, adapt, publish,
                            translate and distribute such material (in whole or
                            in part) worldwide and/or to incorporate it in other
                            works in any form, media or technology now known or
                            hereafter developed for the full term of any
                            copyright that may exist in such material. User also
                            permits any other end user to access, view, store or
                            reproduce the material for that end user's personal
                            use. User hereby grants ROYAL ENFIELD, the right to
                            edit, copy, publish and distribute any material
                            publically made available on the Site by the User.
                            The foregoing provisions of Section 25 apply equally
                            to and are for the benefit of ROYAL ENFIELD, its
                            subsidiaries, affiliates and its third party content
                            providers and licensors and each shall have the
                            right to assert and enforce such provisions directly
                            or on its own behalf.
                        </Text>
                    </div>
                </div>
                <div className="mb-6 lg:mb-8">
                    <Text
                        as="p"
                        weight="bold"
                        font="helvetica"
                        className="text-[1.25rem] mb-6 lg:mb-8 flex gap-5"
                    >
                        {" "}
                        6. TRADEMARKS{" "}
                    </Text>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            {" "}
                            6.1 The Site contain copyrighted material,
                            trademarks and other proprietary information,
                            including, but not limited to, text, software,
                            photos, video, graphics, music, sound, and the
                            entire contents of ROYAL ENFIELD protected by
                            copyright as a collective work under the applicable
                            copyright laws. ROYAL ENFIELD owns a copyright in
                            the selection, coordination, arrangement and
                            enhancement of such content, as well as in the
                            content original to it. Users may not modify,
                            publish, transmit, participate in the transfer or
                            sale, create derivative works, or in any way
                            exploit, any of the content, in whole or in part.
                            Users may download / print / save copyrighted
                            material for the User's personal use only. Except as
                            otherwise expressly stated under copyright law, no
                            copying, redistribution, retransmission, publication
                            or commercial exploitation of downloaded material
                            without the express permission of ROYAL ENFIELD and
                            the copyright owner is permitted. 6.2 If copying,
                            redistribution or publication of copyrighted
                            material is permitted, no changes in or deletion of
                            author attribution, trademark legend or copyright
                            notice shall be made. The User acknowledges that
                            he/she/it does not acquire any ownership rights by
                            downloading copyrighted material. Trademarks that
                            are located within or on the Site or a website
                            otherwise owned or operated in conjunction with
                            ROYAL ENFIELD shall not be deemed to be in the
                            public domain but rather the exclusive property of
                            ROYAL ENFIELD, unless such site is under license
                            from the trademark owner thereof in which case such
                            license is for the exclusive benefit and use of
                            ROYAL ENFIELD, unless otherwise stated.
                        </Text>
                    </div>
                </div>
                <div className="mb-6 lg:mb-8">
                    <Text
                        as="p"
                        weight="bold"
                        font="helvetica"
                        className="text-[1.25rem] mb-6 lg:mb-8 flex gap-5"
                    >
                        {" "}
                        7. INTELLECTUAL PROPERTY RIGHTS COMPLAINTS{" "}
                    </Text>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            {" "}
                            ROYAL ENFIELD respects the intellectual property of
                            others. If you believe that your work has been
                            copied in a way that constitutes any Intellectual
                            Property Right infringement, please address a
                            complaint to the ‘Customer Care’ by way of an email
                            to gearsupport@royalenfield.com.
                        </Text>
                    </div>
                </div>
                <div className="mb-6 lg:mb-8">
                    <Text
                        as="p"
                        weight="bold"
                        font="helvetica"
                        className="text-[1.25rem] mb-6 lg:mb-8 flex gap-5"
                    >
                        {" "}
                        8. USER RESPONSIBILITY AND REGISTRATION OBLIGATIONS{" "}
                    </Text>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            {" "}
                            8.1 If you use the Website as Registered User, you
                            agree that you are competent to contract within the
                            meaning of the Indian Contract Act, 1872. ROYAL
                            ENFIELD reserves the right to terminate your
                            membership and refuse to provide you with access to
                            the Website if it is brought to its notice or if it
                            is discovered that you are under the age of 18 years
                            or for any other reason at ROYAL ENFIELD’s
                            discretion.
                        </Text>
                    </div>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            8.2 If you or ROYAL ENFIELD terminates your use of
                            the Website or any service therein, ROYAL ENFIELD
                            may delete any content or other materials relating
                            to your use of the Site and will have no liability
                            to you or any third party for doing so. You shall be
                            liable to pay for any product that you have already
                            ordered till the time of termination by either party
                            whatsoever .You are solely responsible for
                            maintaining the confidentiality of your User ID and
                            Password. You are responsible for all activities
                            that occur under your User ID and Password. You
                            agree to (a) immediately notify ROYAL ENFIELD of any
                            unauthorized use of your password or account or any
                            other breach of security, and (b) ensure that you
                            exit from your account at the end of each session.
                            ROYAL ENFIELD cannot and will not be liable for any
                            loss or damage arising from your failure to comply
                            with this requirement. You agree, inter-alia, to
                            provide true, accurate, current and complete
                            information about yourself as prompted by Website
                            registration form or provided by You as a Visitor or
                            user of a third party site through which You access
                            the Website. If you provide any information that is
                            untrue, inaccurate, not current or incomplete or we
                            have reasonable grounds to suspect that such
                            information is untrue, inaccurate, not current or
                            incomplete, or not in accordance with the User
                            Agreement, ROYAL ENFIELD has the right to
                            indefinitely suspend or terminate or block access of
                            your membership with the Website and refuse to
                            provide you with access to the Website.
                        </Text>
                    </div>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            8.3 As a condition of purchase, the Site requires
                            your permission to send you administrative and
                            promotional emails. We will send you information
                            regarding your account activity and purchases, as
                            well as updates about our products and promotional
                            offers. You can opt-out of our promotional emails
                            anytime by clicking the unsubscribe link at the
                            bottom of any of our email correspondences. Please
                            see our Privacy Policy for details. The offers made
                            in any promotional messages sent via
                            emails/SMS/WhatsApp/MMS shall be subject to change
                            at the sole discretion of ROYAL ENFIELD and ROYAL
                            ENFIELD owes no responsibility to provide you any
                            information regarding such change.
                        </Text>
                    </div>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            8.4 You undertake not to host, display, upload,
                            modify, publish, transmit, update or share any
                            information that is contained on the website that:
                        </Text>
                    </div>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            1. belongs to another person and to which you does
                            not have any right to;
                        </Text>
                    </div>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            2. is grossly harmful, harassing, blasphemous;
                            defamatory, obscene, pornographic, paedophilic,
                            libellous, invasive of another's privacy, hateful,
                            or racially, ethnically objectionable, disparaging,
                            relating or encouraging money laundering or
                            gambling, or otherwise unlawful in any manner
                            whatever;
                        </Text>
                    </div>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            3. harm minors in any way;
                        </Text>
                    </div>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            4. infringes any patent, trademark, copyright or
                            other proprietary rights;
                        </Text>
                    </div>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            5. violates any law for the time being in force;
                        </Text>
                    </div>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            6. deceives or misleads the addressee about the
                            origin of such messages or communicates any
                            information which is grossly offensive or menacing
                            in nature;
                        </Text>
                    </div>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            7. impersonate another person;
                        </Text>
                    </div>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            8. involves the transmission of "junk mail", "chain
                            letters", or unsolicited mass mailing or "spamming"
                        </Text>
                    </div>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            9. contains software viruses or any other computer
                            code, files or programs designed to interrupt,
                            destroy or limit the functionality of any computer
                            resource;
                        </Text>
                    </div>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            10. threatens the unity, integrity, defence,
                            security or sovereignty of India, friendly relations
                            with foreign states, or public order or causes
                            incitement to the commission of any cognisable
                            offence or prevents investigation of any offence or
                            is insulting any other nation.
                        </Text>
                    </div>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            {" "}
                            That in case it is found that you are in violation
                            of these express conditions, you shall be solely
                            responsible and shall face all legal consequences of
                            the same by yourself and that ROYAL ENFIELD shall in
                            no manner be held responsible for the same.
                        </Text>
                    </div>
                </div>
                <div className="mb-6 lg:mb-8">
                    <Text
                        as="p"
                        weight="bold"
                        font="helvetica"
                        className="text-[1.25rem] mb-6 lg:mb-8 flex gap-5"
                    >
                        {" "}
                        9. BILLING{" "}
                    </Text>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            {" "}
                            9.1. The price of our merchandise as mentioned on
                            Royalenfield.com is the Maximum Retail Price (MRP)
                            for the said product. Such MRP shall be inclusive of
                            all local taxes as are applicable in India.
                            Additional applicable taxes may be charged depending
                            upon the destination where the order has to be
                            shipped to which shall be specified at the time of
                            purchase before payment is effected by you. The tax
                            rate applied and charged upon the order shall
                            include combined tax rate for both state and local
                            tax rates in accordance with the address where the
                            order is being shipped. ROYAL ENFIELD reserves the
                            right to collect taxes and/or such other levy/ duty/
                            surcharge that it may have to incur in addition to
                            the normal taxes it may have to pay. We may also
                            charge Delivery Charges which may include postal
                            charges/ shipment charges etc. that may be
                            applicable for your country.
                        </Text>
                    </div>
                </div>
                <div className="mb-6 lg:mb-8">
                    <Text
                        as="p"
                        weight="bold"
                        font="helvetica"
                        className="text-[1.25rem] mb-6 lg:mb-8 flex gap-5"
                    >
                        {" "}
                        10. ORDER CANCELLATION BY ROYAL ENFIELD{" "}
                    </Text>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            10.1 Due to unavoidable circumstances there may be
                            times when certain orders having been validly placed
                            may not be processed or capable of being dispatched.
                            ROYAL ENFIELD reserves the exclusive right to refuse
                            or cancel any order for any reason. Some situations
                            that may result in your order being cancelled shall
                            include limitations on quantities available for
                            purchase, inaccuracies or errors in product or
                            pricing information, problems identified by our
                            credit and fraud avoidance department or any defect
                            regarding the quality of the product. We may also
                            require additional verifications or information
                            before accepting any order. We will contact you if
                            all or any portion of your order is cancelled or if
                            additional information is required to accept your
                            order. If your order is cancelled after your credit
                            card/ debit card/ any other mode of payment has been
                            charged, the said amount will be reversed into your
                            Account/ as the case may be to the source of the
                            payment within a period of 15 business days. Any
                            type of voucher used in these orders shall be
                            returned and made available to the user in case of
                            cancellation by ROYAL ENFIELD.
                        </Text>
                    </div>
                </div>
                <div className="mb-6 lg:mb-8">
                    <Text
                        as="p"
                        weight="bold"
                        font="helvetica"
                        className="text-[1.25rem] mb-6 lg:mb-8 flex gap-5"
                    >
                        {" "}
                        11. SHIPPING & PROCESSING FEE{" "}
                    </Text>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            11.1. Our shipping and processing charges are
                            intended to compensate ROYAL ENFIELD for the cost of
                            processing your order, handling and packing the
                            products you purchase and delivering them to you.
                            For further information please refer to our Shipping
                            &amp; Payment Policy.
                        </Text>
                    </div>
                </div>
                <div className="mb-6 lg:mb-8">
                    <Text
                        as="p"
                        weight="bold"
                        font="helvetica"
                        className="text-[1.25rem] mb-6 lg:mb-8 flex gap-5"
                    >
                        {" "}
                        12. PAYMENT{" "}
                    </Text>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            12.1 While availing any of the payment method/s
                            offered by us, we are not responsible or take no
                            liability of whatsoever nature in respect of any
                            loss or damage arising directly or indirectly to you
                            including but not limited to the following: (a) lack
                            of authorization for any transaction/s; (b) or
                            exceeding the preset limit mutually agreed by you
                            and between your "Bank/s"; (c) or any payment issues
                            arising out of the transaction; (d) or decline of
                            transaction for any other reason/s. 12.2 All
                            payments made against the purchases/services on
                            Royalenfield.com by you shall be as against the MRP
                            displayed on the website and shall be in terms and
                            conditions of the third party Online Payment Gateway
                            Services as adopted and applicable to your
                            transaction as approved by ROYAL ENFIELD. 12.3
                            Before shipping your order to you, we may request
                            you to provide supporting documents (including but
                            not limited to Govt. issued ID and address proof) to
                            establish the ownership of the payment instrument
                            used by you for your purchase. This is done so as to
                            ensure a safe and a fool proof online shopping
                            environment to our users. 12.4 ROYAL ENFIELD may
                            employ PaisaPay, PayPal and such other third party
                            facilities, for Payments on the Website. Such
                            payments can be made through the electronic or
                            through Cash on delivery transactions, as may be
                            permitted by ROYAL ENFIELD which shall be at its
                            sole discretion. Use of such third party services
                            will be governed by their User Agreement, Seller
                            Terms, Conditions and other rules and policies as
                            may be required and applicable for your nature of
                            activities.
                        </Text>
                    </div>
                </div>
                <div className="mb-6 lg:mb-8">
                    <Text
                        as="p"
                        weight="bold"
                        font="helvetica"
                        className="text-[1.25rem] mb-6 lg:mb-8 flex gap-5"
                    >
                        {" "}
                        13. DELIVERY{" "}
                    </Text>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            {" "}
                            ROYAL ENFIELD endeavors but does not guarantee
                            delivery of products in the stipulated time period
                            as mentioned on the purchase of the product. In no
                            manner can the contract be repudiated if ROYAL
                            ENFIELD fails to deliver any one or more products in
                            the stipulated time frame. However, if you fail to
                            take the delivery of the goods, ROYAL ENFIELD may at
                            its discretion charge you for additional shipping
                            cost. .
                        </Text>
                    </div>
                </div>
                <div className="mb-6 lg:mb-8">
                    <Text
                        as="p"
                        weight="bold"
                        font="helvetica"
                        className="text-[1.25rem] mb-6 lg:mb-8 flex gap-5"
                    >
                        {" "}
                        14. LOSS IN TRANSIT{" "}
                    </Text>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            {" "}
                            All items purchased from ROYAL ENFIELD are made
                            pursuant to a shipment contract. The risk of loss
                            and title for such items purchased on our site pass
                            to you upon our delivery to the carrier.
                        </Text>
                    </div>
                </div>
                <div className="mb-6 lg:mb-8">
                    <Text
                        as="p"
                        weight="bold"
                        font="helvetica"
                        className="text-[1.25rem] mb-6 lg:mb-8 flex gap-5"
                    >
                        {" "}
                        15. REFUNDS & RETURNS{" "}
                    </Text>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            {" "}
                            15.1 ROYAL ENFIELD shall make all endeavors to
                            deliver defect free products to the purchasers.
                            ROYAL ENFIELD does not take title to any returned
                            items purchased by the user unless the item is
                            received by ROYAL ENFIELD. Any item purchased on our
                            website does not qualify for any return unless the
                            product delivered is damaged or has manufacturing
                            defects. The defective and/or damaged goods so
                            received shall be communicated to ROYAL ENFIELD
                            within 48 hours of its receipt. Any communication
                            received after 48 hours of delivery shall not
                            qualify for return unless expressly covered by the
                            product warranty even in case the said product has
                            been wrongly delivered. 15.2 ROYAL ENFIELD holds the
                            sole discretion to determine whether a refund can be
                            issued. For further information please read our
                            Returns &amp; Exchanges Policy. 15.3 No exchange or
                            return is applicable on discounted products unless
                            the product delivered is damaged or has
                            manufacturing defects.
                        </Text>
                    </div>
                </div>
                <div className="mb-6 lg:mb-8">
                    <Text
                        as="p"
                        weight="bold"
                        font="helvetica"
                        className="text-[1.25rem] mb-6 lg:mb-8 flex gap-5"
                    >
                        {" "}
                        16. PRODUCT DESCRIPTIONS{" "}
                    </Text>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            {" "}
                            16.1 Products displayed on ROYAL ENFIELD attempts to
                            be as accurate as possible. However, ROYAL ENFIELD
                            does not warrant that product descriptions or other
                            content is accurate, complete, reliable, current, or
                            error-free. If a product offered by ROYAL ENFIELD is
                            not as described, your sole remedy is to contact
                            ROYAL ENFIELD within 48 hours of receipt and ROYAL
                            ENFIELD reserves the right to provide a solution as
                            per its discretion. ROYAL ENFIELD is not liable to
                            issue any refunds or allow exchanges and/or returns
                            as a matter of policy.
                        </Text>
                    </div>
                </div>
                <div className="mb-6 lg:mb-8">
                    <Text
                        as="p"
                        weight="bold"
                        font="helvetica"
                        className="text-[1.25rem] mb-6 lg:mb-8 flex gap-5"
                    >
                        {" "}
                        17. PRODUCT COMPLIANCE{" "}
                    </Text>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            {" "}
                            Products displayed/ sold on the ROYAL ENFIELD
                            website are manufactured/ procured as per the
                            applicable Local Laws of India and are in conformity
                            with the required Indian industry standards.
                        </Text>
                    </div>
                </div>
                <div className="mb-6 lg:mb-8">
                    <Text
                        as="p"
                        weight="bold"
                        font="helvetica"
                        className="text-[1.25rem] mb-6 lg:mb-8 flex gap-5"
                    >
                        {" "}
                        18. PRODUCT PRICING DISCLAIMER{" "}
                    </Text>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            {" "}
                            The prices displayed on our website may differ from
                            prices that are available in stores. Further the
                            prices displayed in our catalogs are quotes which
                            may vary from country to country for the same
                            product. Prices shown on the website both for India
                            and in other International Countries are subject to
                            change without prior notice. These prices only
                            reflect the MRP and do not include shipping and
                            taxes which may be extra as applicable.
                        </Text>
                    </div>
                </div>
                <div className="mb-6 lg:mb-8">
                    <Text
                        as="p"
                        weight="bold"
                        font="helvetica"
                        className="text-[1.25rem] mb-6 lg:mb-8 flex gap-5"
                    >
                        {" "}
                        19. INACCURACY DISCLAIMER{" "}
                    </Text>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            {" "}
                            From time to time there may be information on our
                            Website or in our catalog that may contain
                            typographical errors, inaccuracies, or omissions
                            that may relate to product descriptions, pricing,
                            and availability. ROYAL ENFIELD reserves the right
                            to correct any errors, inaccuracies or omissions and
                            to change or update information at any time without
                            prior notice.
                        </Text>
                    </div>
                </div>
                <div className="mb-6 lg:mb-8">
                    <Text
                        as="p"
                        weight="bold"
                        font="helvetica"
                        className="text-[1.25rem] mb-6 lg:mb-8 flex gap-5"
                    >
                        {" "}
                        20. WARRANTIES & LIABILITY{" "}
                    </Text>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            21.1 All information, content, materials, products
                            (including software) and other services included on
                            or otherwise made available to you by ROYAL ENFIELD
                            are provided on an AS IS and AS AVAILABLE basis,
                            unless otherwise specified in writing. ROYAL ENFIELD
                            makes no representations or warranties of any kind,
                            express or implied, as to the operation of the
                            services, or the information, content, materials,
                            products (including software) or other services
                            included on or otherwise made available to you
                            through ROYAL ENFIELD, unless otherwise specified in
                            writing. You expressly agree that your use of the
                            website is at your sole risk. 21.2 ROYAL ENFIELD
                            does not warrant that this Website will be
                            uninterrupted, error free, or constantly available,
                            or available at all or that any information on this
                            Website is complete, true, accurate or
                            non-misleading.Further, ROYAL ENFIELD shall not be
                            held responsible for non-availability of the Website
                            during periodic maintenance operations or any
                            unplanned suspension of access to the website that
                            may occur due to technical reasons or for any reason
                            beyond RE control. The user understands and agrees
                            that any material and/or data downloaded or
                            otherwise obtained through the Website is done
                            entirely at their own discretion and risk and they
                            will be solely responsible for any damage to their
                            computer systems or loss of data that results from
                            the download of such material and/or data. 20.3 We
                            will not be liable to you in any way or in relation
                            to the Contents of, or use of, or otherwise in
                            connection with, the Website. You acknowledge, by
                            your use of this Website, that your use of this
                            Website is at your sole risk, that you assume full
                            responsibility for all risks associated with all
                            necessary servicing or repairs of any equipment you
                            use in connection with your use of this Website, and
                            that ROYAL ENFIELD shall not be liable for any
                            damages of any kind related to your use of this
                            Website. 20.4 Though ROYAL ENFIELD shall make all
                            endeavor to protect its websites from any viruses or
                            other illegal use of its website. However we do not
                            warrant that this site; information, Content,
                            materials, product (including software) or services
                            included on or otherwise made available to You
                            through the Website; its servers; or electronic
                            communication sent from us are free of viruses or
                            other harmful components. Nothing on Website
                            constitutes, or is meant to constitute, advice of
                            any kind. 20.5 All the Products sold on Website
                            shall be solely governed by the Indian Laws. In the
                            event we are unable to deliver such Products due to
                            implications of different territorial laws, we will
                            return or will give credit for the amount (if any)
                            received in advance by us from the sale of such
                            Product that could not be delivered to You. It is
                            YOUR responsibility to ensure that the products
                            purchased on this website is not restricted in your
                            territory. ROYAL ENFIELD shall not be responsible
                            for any non-compliance with regard to the local laws
                            of that territory for any product available on this
                            website. 20.6 ROYAL ENFIELD will not be liable for
                            any damages of any kind arising from the use of any
                            service, or from any information, content,
                            materials, products (including software) or from
                            failure of performance, error, omission, inaccuracy,
                            interruption, deletion, defect or delay in operation
                            or transmission, computer virus, communication line
                            failure, theft or destruction or unauthorized
                            access, or alteration, or other services included on
                            or otherwise made available to you through the
                            website, including, but not limited to direct,
                            indirect, incidental, punitive, and consequential
                            damages, unless otherwise specified in writing. You
                            specifically acknowledge that ROYAL ENFIELD is not
                            liable for the defamatory or offensive or illegal
                            conduct of other users or third parties and that the
                            risk of injury from the foregoing rests entirely
                            with you.
                        </Text>
                    </div>
                </div>
                <div className="mb-6 lg:mb-8">
                    <Text
                        as="p"
                        weight="bold"
                        font="helvetica"
                        className="text-[1.25rem] mb-6 lg:mb-8 flex gap-5"
                    >
                        {" "}
                        21. INDEMNITY{" "}
                    </Text>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            You agree to indemnify and shall not hold ROYAL
                            ENFIELD (and its officers, directors, agents,
                            subsidiaries, affiliates, joint ventures, and
                            employees) for any claim or demand, including but
                            not limited to reasonable attorneys’ fees, or
                            arising out of or related to your breach of this
                            T&amp;C, or your violation of these terms, orany law
                            or the rights of a third party or any damage to life
                            and/or property caused by the products delivered.
                        </Text>
                    </div>
                </div>
                <div className="mb-6 lg:mb-8">
                    <Text
                        as="p"
                        weight="bold"
                        font="helvetica"
                        className="text-[1.25rem] mb-6 lg:mb-8 flex gap-5"
                    >
                        {" "}
                        22. BREACH{" "}
                    </Text>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            {" "}
                            22.1 In the event you are found to be in breach of
                            the Terms of Use or Privacy Policy or other rules
                            and policies or if we are unable to verify or
                            authenticate any information you provide or if it is
                            believed that your actions may cause legal liability
                            for you, other users or us, without limiting to the
                            present, without prior notice immediately limit your
                            activity, remove your information,
                            temporarily/indefinitely suspend or terminate or
                            block your membership, and/or refuse to provide you
                            with access to this Website. Any user that has been
                            suspended or blocked may not register or attempt to
                            register with us or use the Website in any manner
                            whatsoever until such time that such user is
                            reinstated by us. 22.2 Notwithstanding the
                            foregoing, if you breach the Terms of Use or Privacy
                            Policy or other rules and policies, we reserve the
                            right to recover any amounts due and owing by you to
                            us and to take strict legal action including but not
                            limited to a referral to the appropriate police or
                            other authorities for initiating criminal or other
                            proceedings against you. 22.3 Any breach of any
                            applicable local laws of that territory shall also
                            result in, without prior notice immediately limit
                            your activity, remove your information,
                            temporarily/indefinitely suspend or terminate or
                            block your membership, and/or refuse to provide you
                            with access to this Website.
                        </Text>
                    </div>
                </div>
                <div className="mb-6 lg:mb-8">
                    <Text
                        as="p"
                        weight="bold"
                        font="helvetica"
                        className="text-[1.25rem] mb-6 lg:mb-8 flex gap-5"
                    >
                        {" "}
                        23. SEVERABILITY{" "}
                    </Text>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            {" "}
                            We reserve the right to make changes to our site,
                            policies, Service Terms, and these Conditions of Use
                            at any time. If any of these conditions shall be
                            deemed invalid, void, or for any reason
                            unenforceable, that condition shall be deemed
                            severable and shall not affect the validity and
                            enforceability of any remaining condition.
                        </Text>
                    </div>
                </div>
                <div className="mb-6 lg:mb-8">
                    <Text
                        as="p"
                        weight="bold"
                        font="helvetica"
                        className="text-[1.25rem] mb-6 lg:mb-8 flex gap-5"
                    >
                        {" "}
                        24. WAIVER
                    </Text>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            {" "}
                            The failure by ROYAL ENFIELD to enforce at any time
                            or for any period any one or more of the terms or
                            conditions of the Agreement shall not be a waiver by
                            ROYAL ENFIELD of them or of the right any time
                            subsequent to enforce all Terms and Conditions of
                            this agreement.
                        </Text>
                    </div>
                </div>
                <div className="mb-6 lg:mb-8">
                    <Text
                        as="p"
                        weight="bold"
                        font="helvetica"
                        className="text-[1.25rem] mb-6 lg:mb-8 flex gap-5"
                    >
                        {" "}
                        25. FORCE MAJEURE{" "}
                    </Text>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            {" "}
                            Failure on the part of ROYAL ENFIELD to perform any
                            of its obligations and the non furnishing of the
                            Service), shall not entitle you to raise any claim
                            against ROYAL ENFIELD or be a breach hereunder to
                            the extent that such failure arises from an event of
                            Force Majeure. If through force Majeure the
                            fulfillment by either party of any obligation set
                            forth in this Agreement will be delayed, the period
                            of such delay will not be counted on in computing
                            periods prescribed by this Agreement. Force Majeure
                            will include any war, civil commotion, strike,
                            governmental action, lockout, accident, epidemic or
                            any other event of any nature or kind whatsoever
                            beyond the control of ROYAL ENFIELD that directly or
                            indirectly hinders or prevents ROYAL ENFIELD from
                            commencing or proceeding with consummation of the
                            transactions contemplated hereby. You expressly
                            agree that lack of funds shall not in any event
                            constitute or be considered an event of Force
                            Majeure.
                        </Text>
                    </div>
                </div>
                <div className="mb-6 lg:mb-8">
                    <Text
                        as="p"
                        weight="bold"
                        font="helvetica"
                        className="text-[1.25rem] mb-6 lg:mb-8 flex gap-5"
                    >
                        {" "}
                        26. DISPUTE RESOLUTION
                    </Text>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            {" "}
                            This agreement shall be construed and the legal
                            relations between YOU and ROYAL ENFIELD hereto shall
                            be determined and governed according to the laws of
                            India. If any dispute arises between You and ROYAL
                            ENFIELD regarding Your use of the Website or Your
                            dealing with ROYAL ENFIELD in relation to any
                            activity on the Website, in connection with the
                            validity, interpretation, implementation or breach
                            of any provision of the Terms &amp; Conditions
                            and/or Privacy Policy including but not limited to
                            the rules and policies contained herein, the dispute
                            shall be subject to the exclusive jurisdiction to
                            the Courts of New Delhi. Your obligations to pay the
                            Payment Fees shall not be suspended during the
                            pendency of such proceedings.
                        </Text>
                    </div>
                </div>
                <div className="mb-6 lg:mb-8">
                    <Text
                        as="p"
                        weight="bold"
                        font="helvetica"
                        className="text-[1.25rem] mb-6 lg:mb-8 flex gap-5"
                    >
                        {" "}
                        27. GRIEVANCE{" "}
                    </Text>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            {" "}
                            Any grievances you have by way of use of the website
                            can be addressed to the ‘Customer Care’ by way of
                            email to support@royalenfield.com The ‘Customer
                            Care’ shall thereafter consider the same and provide
                            a response within one month of the date of such
                            complaint/ grievance.
                        </Text>
                    </div>
                </div>
                <div className="mb-6 lg:mb-8">
                    <Text
                        as="p"
                        weight="bold"
                        font="helvetica"
                        className="text-[1.25rem] mb-6 lg:mb-8 flex gap-5"
                    >
                        {" "}
                        28. GOVERNING LAW
                    </Text>
                    <div className="mb-2">
                        <Text
                            as="p"
                            font="helvetica"
                            size="productTitle2"
                            color="black"
                            weight="light"
                        >
                            These Terms and Conditions or the documents of third
                            party payment channels shall be governed and
                            construed in accordance with the laws of India.
                        </Text>
                    </div>
                </div>
            </div>
        </div>
    );
}
